name: terraform destroy
on: workflow_dispatch
env:
  AWS_KEY: ${{secrets.AWS_KEY}}
  AWS_KEY_PUB: ${{secrets.AWS_KEY_PUB}}

jobs: 
  terraform_plan: 
    name: terraform destroy
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
    steps: 
    - name: checkout
      uses: actions/checkout@v4
    - name: terraform destroy
      run: 
        terraform init
        terraform destroy -auto-approve
