name: terraform destroy
on: workflow_dispatch
env:
  AWS_ACSSES_KEY_ID: ${{secrets.AWS_ACSSES_KEY_ID}}
  AWS_SECRET_ACSSES_KEY_: ${{secrets.AWS_SECRET_ACSSES_KEY}}

jobs: 
  terraform_plan: 
    name: terraform destroy
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
    steps: 
    - name: checkout
      uses: actions/checkout@v4
    - name: terraform destroy
      run: 
        terraform init
        terraform destroy -auto-approve
