name: terraform apply
on: workflow_dispatch


jobs: 
  terraform_plan: 
    name: terraform apply
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
    steps: 
    - name: checkout
      uses: actions/checkout@v4
    - name: terraform apply
      run: 
        terraform init
        terraform apply -auto-approve
