name: terraform apply
on: workflow_dispatch
env:
  AWS_KEY: ${{secrets.AWS_KEY}}
  AWS_KEY_PUB: ${{secrets.AWS_KEY_PUB}}

jobs: 
  terraform_plan: 
    name: terraform apply
    runs_on: ubuntu-latest
    desfauts: 
      run:
        shell: bash
    steps: 
    - name: checkout
      uses: actions/checkout@v4
    - name: terraform apply
      run: 
        terraform init
        terraform apply -auto-approve
